// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapiinvestimento.Context;

#nullable disable

namespace webapiinvestimento.Migrations.Simulacao
{
    [DbContext(typeof(simulacaoContext))]
    [Migration("20251118192704_InicialSimulacao")]
    partial class InicialSimulacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("webapiinvestimento.Models.simulacao", b =>
                {
                    b.Property<int>("ID_SIMULACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DATA_SIMULACAO")
                        .HasColumnType("TEXT");

                    b.Property<int>("ID_CLIENTE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NOME_PRODUTO")
                        .HasColumnType("TEXT");

                    b.Property<int>("PRAZO")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VALOR_FINAL")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VALOR_INVESTIMENTO")
                        .HasColumnType("TEXT");

                    b.HasKey("ID_SIMULACAO");

                    b.ToTable("simulacoesInvestimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
