// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapiinvestimento.Data;

#nullable disable

namespace webapiinvestimento.Migrations.Produto
{
    [DbContext(typeof(produtoContext))]
    [Migration("20251118192846_InicialProduto")]
    partial class InicialProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("webapiinvestimento.Models.produtoInvestimento", b =>
                {
                    b.Property<int>("ID_PRODUTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NOME_PRODUTO")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RENTABILIDADE")
                        .HasColumnType("TEXT");

                    b.Property<string>("RISCO_PRODUTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("TIPO_PRODUTO")
                        .HasColumnType("TEXT");

                    b.HasKey("ID_PRODUTO");

                    b.ToTable("produtoInvestimento");
                });
#pragma warning restore 612, 618
        }
    }
}
